# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionDailySummary',
            fields=[
                ('target_date', models.DateField(primary_key=True, serialize=False)),
                ('total_value', models.DecimalField(decimal_places=1, max_digits=12)),
                ('average_value', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'db_table': 'consumption_daily_summary',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
                ('tariff', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=1, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User')),
            ],
            options={
                'db_table': 'user_consumptions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userconsumption',
            unique_together=set([('user', 'target_datetime')]),
        ),
    ]
