# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionDailySummary',
            fields=[
                ('target_date', models.DateField(primary_key=True, serialize=False)),
                ('total_consumption', models.DecimalField(decimal_places=1, max_digits=12)),
                ('average_consumption', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'db_table': 'consumption_daily_summary',
            },
        ),
        migrations.CreateModel(
            name='UserConsumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('consumption', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'db_table': 'user_consumptions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
                ('tariff', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='userconsumptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='userconsumptions',
            unique_together=set([('user', 'datetime')]),
        ),
    ]
